// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcQVqspFhr1AFl6B9BL5-I_5Mlv1Jwq1U',
    appId: '1:42162399258:web:4f1600c309bfb8ed2989a3',
    messagingSenderId: '42162399258',
    projectId: 'quaizapp-b0c01',
    authDomain: 'quaizapp-b0c01.firebaseapp.com',
    storageBucket: 'quaizapp-b0c01.appspot.com',
    measurementId: 'G-EF4QFB7LCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD90takR42JG0tVTAW9e6MLpQNa550sfcw',
    appId: '1:42162399258:android:2977f3ac195720fd2989a3',
    messagingSenderId: '42162399258',
    projectId: 'quaizapp-b0c01',
    storageBucket: 'quaizapp-b0c01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4tI57TDfSxu40qPk8bbx9Jk8cesthdxE',
    appId: '1:42162399258:ios:8cd7d02301dfc0c82989a3',
    messagingSenderId: '42162399258',
    projectId: 'quaizapp-b0c01',
    storageBucket: 'quaizapp-b0c01.appspot.com',
    iosBundleId: 'com.example.quizMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4tI57TDfSxu40qPk8bbx9Jk8cesthdxE',
    appId: '1:42162399258:ios:8cd7d02301dfc0c82989a3',
    messagingSenderId: '42162399258',
    projectId: 'quaizapp-b0c01',
    storageBucket: 'quaizapp-b0c01.appspot.com',
    iosBundleId: 'com.example.quizMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcQVqspFhr1AFl6B9BL5-I_5Mlv1Jwq1U',
    appId: '1:42162399258:web:5959e17bb0f0748f2989a3',
    messagingSenderId: '42162399258',
    projectId: 'quaizapp-b0c01',
    authDomain: 'quaizapp-b0c01.firebaseapp.com',
    storageBucket: 'quaizapp-b0c01.appspot.com',
    measurementId: 'G-VQHQPGBFK0',
  );
}
