// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7iW9UUXC1Q1LlvT_9_HXi9f9HLMumtbo',
    appId: '1:902374159906:web:412ec20f8e57b42b957c7b',
    messagingSenderId: '902374159906',
    projectId: 'bgquiz-ef282',
    authDomain: 'bgquiz-ef282.firebaseapp.com',
    storageBucket: 'bgquiz-ef282.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYwASdHBucO1jQ2Pp0bN7HfmHQr0sZtEg',
    appId: '1:902374159906:android:9cb4f0604baf28df957c7b',
    messagingSenderId: '902374159906',
    projectId: 'bgquiz-ef282',
    storageBucket: 'bgquiz-ef282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvzmkjthVySgBowPBqHMh_Rw5XRzBDhpg',
    appId: '1:902374159906:ios:e7842036fb19619c957c7b',
    messagingSenderId: '902374159906',
    projectId: 'bgquiz-ef282',
    storageBucket: 'bgquiz-ef282.appspot.com',
    iosBundleId: 'com.example.quizMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4tI57TDfSxu40qPk8bbx9Jk8cesthdxE',
    appId: '1:42162399258:ios:8cd7d02301dfc0c82989a3',
    messagingSenderId: '42162399258',
    projectId: 'quaizapp-b0c01',
    storageBucket: 'quaizapp-b0c01.appspot.com',
    iosBundleId: 'com.example.quizMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7iW9UUXC1Q1LlvT_9_HXi9f9HLMumtbo',
    appId: '1:902374159906:web:dd85a15c8e2a9a99957c7b',
    messagingSenderId: '902374159906',
    projectId: 'bgquiz-ef282',
    authDomain: 'bgquiz-ef282.firebaseapp.com',
    storageBucket: 'bgquiz-ef282.appspot.com',
  );
}